name: Build and Add Link

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.ref
        run: echo ${{ github.event.pull_request.head.ref }}

      - uses: actions/checkout@v5
        name: checkout
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build (and test) project with Maven
        run: mvn -B test --file pom.xml

